public_key=
private_key=
org_id=
project_name=
cluster_name= "mongodb-devops-cluster"
cloud_provider = "aws"
region="US_EAST_1"
mongodbversion="3.6.0"
dbuser="user"
dbuser_password=user
database_name="devops-db"
ip_address="0.0.0.0"
provider_instance_size_name="M10"
cloud_backup = false // set to true for production workload